// import React, { useState } from 'react';
// import { useNavigate } from 'react-router-dom';

// const Login = () => {
//   const [email, setEmail] = useState('');
//   const [password, setPassword] = useState('');
//   const [error, setError] = useState('');
//   const navigate = useNavigate();

//   const handleSubmit = (e) => {
//     e.preventDefault();
//     setError('');
    
//     if (email && password) {
//       localStorage.setItem('crm-user', JSON.stringify({
//         id: 1,
//         email: email,
//         name: 'Admin User',
//         role: 'Administrator'
//       }));
//       navigate('/dashboard');
//     } else {
//       setError('Please enter email and password');
//     }
//   };

//   return (
//     <div style={{
//       minHeight: '100vh',
//       display: 'flex',
//       alignItems: 'center',
//       justifyContent: 'center',
//       backgroundColor: '#f9fafb',
//       padding: '20px',
//     }}>
//       <div style={{
//         backgroundColor: 'white',
//         borderRadius: '12px',
//         boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
//         padding: '40px',
//         width: '100%',
//         maxWidth: '400px',
//       }}>
//         <div style={{ textAlign: 'center', marginBottom: '32px' }}>
//           <h2 style={{ fontSize: '28px', fontWeight: '700', color: '#111827', marginBottom: '8px' }}>
//             Welcome to your CRM app!
//           </h2>
//           <p style={{ fontSize: '14px', color: '#6b7280' }}>
//             React.js/Node.js app generated by the Flatlogic Web App Generator
//           </p>
//         </div>
        
//         <form onSubmit={handleSubmit} style={{ marginBottom: '32px' }}>
//           {error && (
//             <div style={{
//               backgroundColor: '#fee2e2',
//               border: '1px solid #fca5a5',
//               color: '#dc2626',
//               padding: '12px',
//               borderRadius: '6px',
//               marginBottom: '16px',
//               fontSize: '14px',
//             }}>
//               {error}
//             </div>
//           )}
          
//           <div style={{ marginBottom: '20px' }}>
//             <label style={{ display: 'block', fontSize: '14px', fontWeight: '500', color: '#374151', marginBottom: '6px' }}>
//               Email address
//             </label>
//             <input
//               type="email"
//               placeholder="Email address"
//               value={email}
//               onChange={(e) => setEmail(e.target.value)}
//               required
//               className="form-input"
//             />
//           </div>
          
//           <div style={{ marginBottom: '20px' }}>
//             <label style={{ display: 'block', fontSize: '14px', fontWeight: '500', color: '#374151', marginBottom: '6px' }}>
//               Password
//             </label>
//             <input
//               type="password"
//               placeholder="Password"
//               value={password}
//               onChange={(e) => setPassword(e.target.value)}
//               required
//               className="form-input"
//             />
//           </div>

//           <button type="submit" className="btn-primary" style={{ width: '100%', padding: '12px' }}>
//             Sign in
//           </button>
//         </form>
        
//         <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', textAlign: 'center' }}>
//           <div style={{ padding: '12px', border: '1px solid #e5e7eb', borderRadius: '6px' }}>
//             <div style={{ fontSize: '14px', fontWeight: '600', color: '#111827', marginBottom: '4px' }}>
//               React.js
//             </div>
//             <div style={{ fontSize: '12px', color: '#6b7280' }}>
//               Frontend
//             </div>
//           </div>
//           <div style={{ padding: '12px', border: '1px solid #e5e7eb', borderRadius: '6px' }}>
//             <div style={{ fontSize: '14px', fontWeight: '600', color: '#111827', marginBottom: '4px' }}>
//               Node.js
//             </div>
//             <div style={{ fontSize: '12px', color: '#6b7280' }}>
//               Backend
//             </div>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default Login;