// import React from 'react';

// const Dashboard = () => {
//   const stats = [
//     { title: "Users", value: "3", change: "+2" },
//     { title: "Contacts", value: "5", change: "+1" },
//     { title: "Leads", value: "8", change: "+3" },
//   ];

//   return (
//     <div>
//       <div style={{ marginBottom: '24px' }}>
//         <h1 style={{ fontSize: '24px', fontWeight: '700', color: '#111827' }}>
//           Dashboard
//         </h1>
//       </div>

//       <div style={{ 
//         display: 'grid', 
//         gridTemplateColumns: '1fr', 
//         gap: '20px', 
//         marginBottom: '24px' 
//       }}>
//         {stats.map((stat, index) => (
//           <div key={index} className="card">
//             <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
//               <div>
//                 <p style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>
//                   {stat.title}
//                 </p>
//                 <p style={{ fontSize: '24px', fontWeight: '600', color: '#111827' }}>
//                   {stat.value}
//                 </p>
//               </div>
//               <div style={{
//                 backgroundColor: '#d1fae5',
//                 color: '#065f46',
//                 fontSize: '12px',
//                 fontWeight: '500',
//                 padding: '4px 8px',
//                 borderRadius: '4px',
//               }}>
//                 {stat.change}
//               </div>
//             </div>
//           </div>
//         ))}
//       </div>

//       <div className="card">
//         <h2 style={{ fontSize: '18px', fontWeight: '600', color: '#111827', marginBottom: '12px' }}>
//           Create Chart or Widget
//         </h2>
//         <p style={{ fontSize: '14px', color: '#6b7280', marginBottom: '20px', lineHeight: '1.5' }}>
//           Describe your new widget or chart in natural language. For example: 
//           "Number of admin users" OR "red chart with number of closed contracts grouped by month"
//         </p>
        
//         <div style={{
//           border: '2px dashed #d1d5db',
//           borderRadius: '8px',
//           padding: '40px',
//           textAlign: 'center',
//         }}>
//           <p style={{ color: '#9ca3af', fontSize: '14px' }}>
//             Chart/Widget creation area
//           </p>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default Dashboard;












import React from 'react';

const Dashboard = () => {
  const stats = [
    { value: "1,254", label: "Total Users", change: "+12% this month" },
    { value: "$48,560", label: "Revenue", change: "+8% this month" },
    { value: "367", label: "New Leads", change: "+15% this month" },
    { value: "89%", label: "Conversion Rate", change: "+2% this month" },
  ];

  const activities = [
    { time: "9:15 AM", description: "Monthly report generated by system" },
    { time: "Yesterday", description: "Meeting with ABC Company by sales" },
    { time: "2 days ago", description: "New product launched by marketing" },
    { time: "3 days ago", description: "Website maintenance completed by tech" },
  ];

  const months = ["Month 1", "Month 2", "Month 3", "Month 4", "Month 5", "Month 6", "Month 7"];

  return React.createElement('div', {
    style: {
      padding: '24px',
      backgroundColor: '#f3f4f6',
      minHeight: '100vh',
      fontFamily: 'system-ui, -apple-system, sans-serif'
    }
  },
    // Header/Welcome Section
    React.createElement('div', { style: { marginBottom: '24px' } },
      React.createElement('h1', {
        style: {
          fontSize: '28px',
          fontWeight: '700',
          color: '#111827',
          marginBottom: '8px'
        }
      }, 'CRM Dashboard'),
      
      React.createElement('h2', {
        style: {
          fontSize: '20px',
          fontWeight: '500',
          color: '#4b5563',
          marginBottom: '16px'
        }
      }, 'Dashboard'),
      
      React.createElement('p', {
        style: {
          fontSize: '16px',
          color: '#6b7280'
        }
      }, 'Welcome back, Admin User')
    ),

    // Stats Grid - 4 cards in a row
    React.createElement('div', {
      style: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: '20px',
        marginBottom: '32px'
      }
    },
      stats.map((stat, index) =>
        React.createElement('div', {
          key: index,
          style: {
            backgroundColor: 'white',
            borderRadius: '12px',
            padding: '20px',
            boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
          }
        },
          React.createElement('div', { style: { textAlign: 'center' } },
            React.createElement('p', {
              style: {
                fontSize: '32px',
                fontWeight: '700',
                color: '#111827',
                marginBottom: '8px'
              }
            }, stat.value),
            
            React.createElement('p', {
              style: {
                fontSize: '14px',
                color: '#6b7280',
                marginBottom: '4px'
              }
            }, stat.label),
            
            React.createElement('p', {
              style: {
                fontSize: '14px',
                color: '#10b981',
                fontWeight: '500'
              }
            }, stat.change)
          )
        )
      )
    ),

    // Monthly Revenue and Recent Activity Section
    React.createElement('div', {
      style: {
        display: 'grid',
        gridTemplateColumns: '2fr 1fr',
        gap: '20px'
      }
    },
      // Monthly Revenue Card
      React.createElement('div', {
        style: {
          backgroundColor: 'white',
          borderRadius: '12px',
          padding: '24px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
        }
      },
        React.createElement('div', {
          style: {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '24px'
          }
        },
          React.createElement('h3', {
            style: {
              fontSize: '18px',
              fontWeight: '600',
              color: '#111827'
            }
          }, 'Monthly Revenue'),
          
          React.createElement('span', {
            style: {
              fontSize: '14px',
              color: '#6b7280',
              backgroundColor: '#f3f4f6',
              padding: '4px 12px',
              borderRadius: '20px',
              cursor: 'pointer'
            }
          }, 'Last 6 Months ▼')
        ),

        // Chart Bars
        React.createElement('div', {
          style: {
            height: '200px',
            marginBottom: '16px',
            display: 'flex',
            alignItems: 'flex-end',
            gap: '12px'
          }
        },
          months.map((month, index) =>
            React.createElement('div', {
              key: index,
              style: {
                flex: 1,
                height: `${60 + (index * 15)}px`,
                backgroundColor: index === 5 ? '#3b82f6' : '#93c5fd',
                borderRadius: '6px 6px 0 0',
                transition: 'height 0.3s'
              }
            })
          )
        ),

        // Month Labels
        React.createElement('div', {
          style: {
            display: 'flex',
            gap: '12px',
            borderTop: '1px solid #e5e7eb',
            paddingTop: '16px'
          }
        },
          months.map((month, index) =>
            React.createElement('div', {
              key: index,
              style: {
                flex: 1,
                fontSize: '14px',
                color: '#6b7280',
                textAlign: 'center'
              }
            }, month)
          )
        )
      ),

      // Recent Activity Card
      React.createElement('div', {
        style: {
          backgroundColor: 'white',
          borderRadius: '12px',
          padding: '24px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
        }
      },
        React.createElement('h3', {
          style: {
            fontSize: '18px',
            fontWeight: '600',
            color: '#111827',
            marginBottom: '20px'
          }
        }, 'Recent Activity'),
        
        activities.map((activity, index) =>
          React.createElement('div', {
            key: index,
            style: {
              padding: '12px 0',
              borderBottom: index < activities.length - 1 ? '1px solid #e5e7eb' : 'none'
            }
          },
            React.createElement('p', {
              style: {
                fontSize: '14px',
                fontWeight: '500',
                color: '#111827',
                marginBottom: '4px'
              }
            }, activity.time),
            
            React.createElement('p', {
              style: {
                fontSize: '14px',
                color: '#6b7280',
                lineHeight: '1.5'
              }
            }, activity.description)
          )
        )
      )
    )
  );
};

export default Dashboard;